blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('media/Files/<int:pk>',PostDeleteView.as_view(),name='post-delete' ),
    path('search/',views.search,name='search' ),
    path('about/', views.about, name='blog-about'),
]

django_web_app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),

    #path('login/', user_views.login, name='register'),

    path('book/', include('books.urls')),
    path('borrows/', include('borrow.urls')),


    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='users/password_change.html'), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
import os

class Post(models.Model):
	title = models.CharField(max_length=200)
	file = models.FileField(null=True,blank=True,upload_to='Files')
	content = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

	def extension(self):
		name, extension = os.path.splitext(self.file.name)
		return extension

	def get_absolute_url(self):
		return reverse('post-detail', kwargs={'pk': self.pk})

        

books/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Book(models.Model):
    code = models.CharField(max_length=20, unique=True)  # Mã số sách
    title = models.CharField(max_length=200)             # Tên sách
    author = models.CharField(max_length=100)            # Tác giả
    year = models.PositiveIntegerField()                 # Năm xuất bản
    publisher = models.CharField(max_length=100)         # Nhà xuất bản
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    description = models.TextField(blank=True)           # Mô tả
    quantity = models.PositiveIntegerField()             # Số lượng
    price = models.DecimalField(max_digits=10, decimal_places=2)  # Đơn giá

    def __str__(self):
        return f"{self.title} - {self.author}"

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User, Group
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
import operator
from django.urls import reverse_lazy
from django.contrib.staticfiles.views import serve
from django.conf import settings
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model



def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)

def search(request):
    query = request.GET.get('q')
    result = Post.objects.filter(
        Q(title__icontains=query) | Q(author__username__icontains=query) | Q(content__icontains=query)
    )
    paginator = Paginator(result, 8)  # 2 bài mỗi trang
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'posts': page_obj}
    return render(request, 'blog/home.html', context)
   


def getfile(request):
   return serve(request, 'File')


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 6


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 6

    def get_queryset(self):
        user = get_object_or_404(get_user_model(), username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/post_form.html'
    fields = ['title', 'content', 'file']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'blog/post_form.html'
    fields = ['title', 'content', 'file']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author or self.request.user.groups.filter(name='Admin').exists():
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog-home')  # Thay 'blog-home' bằng tên URL của bạn cho trang chủ
    template_name = 'blog/post_confirm_delete.html'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author or self.request.user.groups.filter(name='Admin').exists():
            return True
        return False
    
    def delete(self, request, *args, **kwargs):
        post = self.get_object()
        if post.file:  # Giả sử trường file trong model là 'file'
            post.file.delete()
        return super().delete(request, *args, **kwargs)

def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >
    <link rel="stylesheet" href="{% static 'blog/test.css' %}">
    {% if title %}
        <title>22162009 - {{title}}</title>
    {% else %}
        <title>22162009</title>
    {% endif %}

</head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand font-weight-bold" href="{% url 'blog-home' %}"><i class="fas fa-file"></i> 22162009</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'blog-home' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
                    </li>
                  </ul>
                  <ul class="navbar-nav mr-auto">                
                    {% if user.is_authenticated and user.role.name == "Librarian" %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'book_list' %}"><i class="fas fa-book"></i> Quản lý sách</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'category_list' %}"><i class="fas fa-list"></i> Quản lý thể loại</a>
                      </li>
                    {% endif %}
                    
                    {% if user.is_authenticated and user.role.name in 'Staff,Teacher,Librarian' %}
                      <li class="nav-item"><a class="nav-link" href="{% url 'borrow_slip_list' %}"><i class="fas fa-list"></i>📚 Quản lý phiếu mượn sách</a></li>
                    {% endif %}

                    {% if user.is_authenticated and user.role.name in 'Student' %}
                      <li class="nav-item"><a class="nav-link" href="{% url 'borrow_slip_list' %}"><i class="fas fa-list"></i>Mượn sách 📗</a></li>
                    {% endif %}
                  </ul>
                  
                  <!------{{ request.get_host }}/blog/search/-->
                  <form id="searchform" action="{% url 'search' %}" method="get">
                    <input type="text" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search Here..." />
                    <button type="button" onclick="searchform.submit()" class=" text-white my-color btn-primary"><i class="fa fa-search"></i></button>
                  </form>
              
                    {% if user.is_authenticated %}
                    <a href="{% url 'user-posts' user %}" class="btn text-white m-2"><i class="fas fa-user-shield"></i> My Post</a>
                    <a href="{% url 'post-create' %} " class="btn text-white m-2"><i class="fas fa-user-edit"></i> New Post</a>
                    <a href="{% url 'profile' %} " class="btn text-white m-2"><i class="fas fa-user"></i> {{ user.username }}</a>
                    <a href="{% url 'login' %} " class="btn text-white m-2"><i class="fas fa-sign-out-alt"></i> Log Out</a>
                    
                    {% else %}
                    <a href="{% url 'login' %} " class="btn text-white m-2"><i class="fas fa-user-tie"></i> Log In</a>
                   
                    <a href="{% url 'register' %} " class="btn text-white m-2"> <i class="fas fa-sign-in-alt"></i> Sign Up</a>
                    {% endif %}
                  
                </div>
              </nav>
      <div class="container my-bg">
        {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
          {% endfor %}
        {% endif %}
    {% block content %}
      
    {% endblock  %}
</div> 
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'blog/main.js' %}"></script>
  </body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="row" style="min-height: 80vh;">
        {% for post in posts %}
        <div class="col-lg-6 mb-4" style="max-height: 20vh;">  <!-- Tăng max-height nếu cần -->
            <!-- Card container with background image -->
            <div class="card bg-white shadow-lg position-relative" style="background-size: cover; background-position: center;">
                
                <div class="card-body">
                    <!-- Profile image and metadata -->
                    <div class="d-flex align-items-center">
                        <a href="{{ post.author.profile.image.url }}" target="_blank">
                            <img src="{{ post.author.profile.image.url }}" alt="{{ post.author }}" class="rounded-circle img-thumbnail img-fluid shadow-sm" style="width: 50px; height: 50px;">
                        </a>
                        <div class="ml-3">
                            <a href="{% url 'user-posts' post.author.username %}" class="text-dark">
                                <h5 class="mb-1">{{ post.author }}</h5>
                            </a>
                            <small class="text-muted">{{ post.date_upload|date:"F d, Y" }}</small>
                        </div>
                    </div>

                    <!-- Post title with link to post detail -->
                    <h2 class="mt-3">
                        <a href="{% url 'post-detail' post.id %}" class="text-dark">{{ post.title }}</a>
                    </h2>

                    <!-- Post content preview -->
                    <p class="text-justify text-truncate mt-2">{{ post.content }}</p>

                    <!-- Blog file section (if exists) -->
                    {% if post.file %}
                        <div class="mt-3">
                            <a href="{{ post.file.url }}" download class="btn btn-outline-primary">
                                <i class="fas fa-download"></i> Download
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Pagination -->
    {% if is_paginated %}
    <div class="pagination-container mt-4">
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info" href="?page=1">First</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        
        {% if page_obj.has_next %}
            <a class="btn btn-outline-info" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    </div>
    {% endif %}
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container mt-4" style="min-height: 20vh;">
    <!-- Post Header -->
    <div class="row mb-4">
        <div class="col-lg-8 mx-auto">
            <div class="media shadow-lg p-4 mb-4 bg-white rounded">
                <!-- Author Avatar and Link -->
                <a href="{{ object.author.profile.image.url }}" target="_blank">
                    <img src="{{ object.author.profile.image.url }}" alt="{{ object.author }}" class="rounded-circle img-thumbnail img-fluid" style="width: 70px; height: 70px;">
                </a>
                <div class="media-body ml-3">
                    <!-- Author and Date -->
                    <h3 class="mt-0">
                        <a href="{% url 'user-posts' object.author.username %}" class="text-dark">{{ object.author }}</a>
                    </h3>
                    <small class="text-muted">{{ object.date_upload|date:"F d, Y" }}</small>
                </div>
                <!-- Actions if user is the author -->
                {% if object.author == user %}
                    <div class="ml-3 d-flex align-items-center">
                        <a href="{% url 'post-update' object.id %}" class="btn btn-secondary btn-sm mr-2">Update</a>
                        <a href="{% url 'post-delete' object.id %}" class="btn btn-danger btn-sm">Delete</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Post Content -->
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <article class="shadow-lg bg-white p-4 rounded">
                <h2 class="post-title">{{ object.title }}</h2>
                <hr>

                <!-- Display post content -->
                <div class="post-content">
                    <p>{{ object.content }}</p>
                </div>

                <!-- Display file (if exists) -->
                {% if object.file %}
                    <div class="mt-4">
                        {% if object.extension == '.jpg' or object.extension == 'jpeg' or object.extension == '.png' %}
                            <a href="{{ object.file.url }}" download>
                                <img src="{{ object.file.url }}" alt="Post Image" class="img-fluid">
                            </a>
                            <h5 class="mt-2"><a href="{{ object.file.url }}" download>{{ object.file }}</a></h5>
                        {% elif object.extension == '.mp4' %}
                            <div class="embed-responsive embed-responsive-16by9">
                                <video id="video-1_html_api" class="vjs-tech" preload="auto" controls>
                                    <source src="{{ object.file.url }}" type="video/mp4">
                                </video>
                            </div>
                            <a href="{{ object.file.url }}" download class="mt-2">{{ object.file }}</a>
                        {% else %}
                            <a href="{{ object.file.url }}" download class="text-dark">{{ object.file }}</a>
                        {% endif %}
                    </div>
                {% endif %}
            </article>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section pt-2 mt-3 shadow-lg"  >
          <form action="" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <fieldset class="form-group">
                    <legend class="border-bottom mb-4">
                        Post
                    </legend>
                    {{ form|crispy }}
              </fieldset>
              <div class="form-group">
                  
                  <button class="btn btn-outline-primary" type="submit"><i class="fas fa-upload"></i> Upload</button>
              </div>
          </form>
         
      </div>
{% endblock content %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% block content %}
<p>Posts containing '{{query_string}}'</p> 
{% for post in posts %}
    <div>
        <span> {{ post.created }} </span>
        <a href="{% url 'post_detail' slug=post.slug %}"><h2 class="page-title">{{ post.title }}</h2></a>
        <div class="post">
            {{ post.body|safe }}
        </div>
    </div>
{% endfor %}
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}
    {% endif %}
{% endblock content %}